/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\computer.gltf 
Author: Cybertron B-127 (https://sketchfab.com/robo-reboot)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/computer-c60f2c0d316246aea5eb3031291b9842
Title: Computer
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/computer.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials.material} position={[0.291, 0.108, 0.295]} scale={[0.703, 0.409, 0.001]} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.material_1} position={[-0.133, -0.07, 0.309]} scale={[0.675, 0.387, 0.001]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.material_2} position={[0.39, -0.155, 0.325]} scale={[0.556, 0.319, 0.001]} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.material_3} position={[-0.411, -0.169, 0.359]} scale={[0.494, 0.276, 0.001]} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.material_4} position={[-0.346, 0.137, 0.3]} scale={[0.668, 0.379, 0.001]} />
    </group>
  )
}

useGLTF.preload('/computer.gltf')
